### PR TITLE
High-Five skillTrees Changes:

### PR DESCRIPTION
**Pull request by maneco2**
- Updated Skills/Forgotten Acquisition Level
- AutoLearnForgottenScrollSkills = True at
the correct level
- Updated Skill Acquisition SP
- Add missing skill High Five Skill Acquisition
- Reorganized Skill Acquisition by Level
- 6/6 Races (All Classes)

High Five part 5 skills changes:
http://l2db.info/
http://l2central.info/

### CODE REVIEW

**Comment by maneco2** [comment]
is not all for skill ID

**Comment by maneco2** [comment]
High-Five skilltrees finished

**Comment by maneco2** [comment]
[code]<skill id="912" levels="1" name="Summon Imperial Phoenix">
    <set name="hitTime" val="15000" />
    <set name="icon" val="icon.skill0912" />
    <set name="isMagic" val="1" /> 
    <set name="itemConsumeCount" val="2" />
    <set name="itemConsumeId" val="1461" /> 
    <set name="magicLvl" val="81" />
    <set name="mpConsume" val="145" />
    <set name="operateType" val="A1" />
    <set name="reuseDelay" val="45000" />
    <set name="rideState" val="NONE;STRIDER;WYVERN;WOLF" />
    <set name="targetType" val="SELF" />
    <cond>
        <player canSummon="true" />
    </cond>
    <for>
        <effect name="Summon">
            <param npcId="14918" />
            <param consumeItemId="1461" consumeItemCount="1" />
            <param lifeTime="3600" />
        </effect>
    </for>
</skill>[/code]

**Comment by maneco2** [comment]
Minor update previous update.

**Comment by Zoey76** [comment]
I checked the Pull Request, I need to know where you got SP values.

**Comment by maneco2** [comment]
This information you find in the description of Pull Request :D

**Pull request closed without merging**
