### PR TITLE
Update Q00234_FatesWhisper.java

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Sacrifice78** [comment]
Thanks

**Comment by Sacrifice78** [comment]
Thank you
https://github.com/L2J/L2J_DataPack/commit/b4dbd36f33f67fe5b87d8ac8c2771b694b9f0771

**Comment by Sacrifice78** [comment]
Yes, this is another solution more easy.
https://github.com/L2J/L2J_DataPack/pull/294

**Comment by Zoey76** [comment]
This HTML is returned in a simple NPC Chat window and not on a quest window (showing the reward).

**Comment by Zoey76** [comment]
Fixed in https://github.com/L2J/L2J_DataPack/commit/1201b67f9258536f3c8631d29e2120d1a6e13c88

**Pull request closed without merging**
