### PR TITLE
Sacrifice's DataPack Updates and/or Implementations

### PR DESCRIPTION
**Pull request by Sacrifice78**
-- Added line in scripts.cfg for start AI. Removed Carrier Return and
Line Feed at the end of file.
-- Added new AI for High Five Treasure Chests (thanks @HorridoJoho
:+1:). @HorridoJoho, fixed line 69 from your last file in post
http://www.l2jserver.com/forum/viewtopic.php?f=104&t=27501
-- Removed unnecessary imports, variables and methods in OpenChest.java.
Removed Carrier Return and Line Feed at the end of file.
-- Added new spawn locations for H5 Treasure Chests and removed old
locations by duplicity. Removed Carrier Return and Line Feed at the end
of file.

### CODE REVIEW

**Comment by Sdwz** [comment]
I don't mean to be rude, really, but :
- Your AI isn't quite right in terms of structures, please make sure to review some other AI (that main method...)
- Skill effect should stay in effect really. I understand it light be more convenient for you but just no
- Retail handles drop reward with AI, not drop list

**Comment by Sacrifice78** [comment]
Okey... I will update... according to your... comments. Its totally true that its a fastest implementation and dont take sufficient care with the "important L2J **Conventions".** By the other hand, @Sdwz thanks for at least do any comment.

**Comment by Sacrifice78** [comment]
Ok? @Sdwz

**Comment by Sacrifice78** [comment]
I'm finish!.

**Pull request closed without merging**
