### PR TITLE
Ertheia

### PR DESCRIPTION
**Pull request by ChaosPaladin**

### CODE REVIEW

**Comment by Gladicek** [comment]
So many merge pull requests....thats gonna mess up commits :D

**Comment by ChaosPaladin** [comment]
I don't know how it happened and how to get a lot of PR =(

**Comment by Gladicek** [comment]
Just make new one repository (fork) and put your changes in that. After you can PR without any this crap around :)

**Comment by UnAfraid** [comment]
Instead of reforking just rebase to l2j read that http://robots.thoughtbot.com/keeping-a-github-fork-updated

**Pull request closed without merging**
