### PR TITLE
Update announcements and New Classes Expertise

### PR DESCRIPTION
**Pull request by maneco2**

### CODE REVIEW

**Comment by NosBit** [comment]
Can you merge the commits with same message?

**Comment by maneco2** [comment]
i not understand you

**Comment by St3eT** [comment]
Do 1 or 2 commit instead of 939399393874829

**Comment by maneco2** [comment]
continued without understanding, sorry, I will not translating to try to understand you

**Comment by Gladicek** [comment]
You rly should learn atleast eng. basics. Just merge these commit into one...

**Comment by UnAfraid** [comment]
Rebase your fork before starting new pull request.
Also this should be inside one common skill tree instead of everywhere

**Pull request closed without merging**
